// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: internal/proto/upload/upload.proto

package upload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UploadServiceClient is the client API for UploadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploadServiceClient interface {
	CreatePresignedUrl(ctx context.Context, in *CreatePresignedUrlRequest, opts ...grpc.CallOption) (*CreatePresignedUrlResponse, error)
	UploadedWebhook(ctx context.Context, in *UploadedWebhookRequest, opts ...grpc.CallOption) (*UploadedWebhookResponse, error)
}

type uploadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadServiceClient(cc grpc.ClientConnInterface) UploadServiceClient {
	return &uploadServiceClient{cc}
}

func (c *uploadServiceClient) CreatePresignedUrl(ctx context.Context, in *CreatePresignedUrlRequest, opts ...grpc.CallOption) (*CreatePresignedUrlResponse, error) {
	out := new(CreatePresignedUrlResponse)
	err := c.cc.Invoke(ctx, "/upload.UploadService/CreatePresignedUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadServiceClient) UploadedWebhook(ctx context.Context, in *UploadedWebhookRequest, opts ...grpc.CallOption) (*UploadedWebhookResponse, error) {
	out := new(UploadedWebhookResponse)
	err := c.cc.Invoke(ctx, "/upload.UploadService/UploadedWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadServiceServer is the server API for UploadService service.
// All implementations must embed UnimplementedUploadServiceServer
// for forward compatibility
type UploadServiceServer interface {
	CreatePresignedUrl(context.Context, *CreatePresignedUrlRequest) (*CreatePresignedUrlResponse, error)
	UploadedWebhook(context.Context, *UploadedWebhookRequest) (*UploadedWebhookResponse, error)
	mustEmbedUnimplementedUploadServiceServer()
}

// UnimplementedUploadServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUploadServiceServer struct {
}

func (UnimplementedUploadServiceServer) CreatePresignedUrl(context.Context, *CreatePresignedUrlRequest) (*CreatePresignedUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePresignedUrl not implemented")
}
func (UnimplementedUploadServiceServer) UploadedWebhook(context.Context, *UploadedWebhookRequest) (*UploadedWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadedWebhook not implemented")
}
func (UnimplementedUploadServiceServer) mustEmbedUnimplementedUploadServiceServer() {}

// UnsafeUploadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploadServiceServer will
// result in compilation errors.
type UnsafeUploadServiceServer interface {
	mustEmbedUnimplementedUploadServiceServer()
}

func RegisterUploadServiceServer(s grpc.ServiceRegistrar, srv UploadServiceServer) {
	s.RegisterService(&UploadService_ServiceDesc, srv)
}

func _UploadService_CreatePresignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePresignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadServiceServer).CreatePresignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/upload.UploadService/CreatePresignedUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadServiceServer).CreatePresignedUrl(ctx, req.(*CreatePresignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UploadService_UploadedWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadedWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadServiceServer).UploadedWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/upload.UploadService/UploadedWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadServiceServer).UploadedWebhook(ctx, req.(*UploadedWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UploadService_ServiceDesc is the grpc.ServiceDesc for UploadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UploadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "upload.UploadService",
	HandlerType: (*UploadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePresignedUrl",
			Handler:    _UploadService_CreatePresignedUrl_Handler,
		},
		{
			MethodName: "UploadedWebhook",
			Handler:    _UploadService_UploadedWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/upload/upload.proto",
}
