// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: internal/proto/upload/upload.proto

package upload

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UploadClient is the client API for Upload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UploadClient interface {
	CreatePresignedUrl(ctx context.Context, in *CreatePresignedUrlRequest, opts ...grpc.CallOption) (*CreatePresignedUrlResponse, error)
	UploadedWebhook(ctx context.Context, in *UploadedWebhookRequest, opts ...grpc.CallOption) (*UploadedWebhookResponse, error)
}

type uploadClient struct {
	cc grpc.ClientConnInterface
}

func NewUploadClient(cc grpc.ClientConnInterface) UploadClient {
	return &uploadClient{cc}
}

func (c *uploadClient) CreatePresignedUrl(ctx context.Context, in *CreatePresignedUrlRequest, opts ...grpc.CallOption) (*CreatePresignedUrlResponse, error) {
	out := new(CreatePresignedUrlResponse)
	err := c.cc.Invoke(ctx, "/upload.Upload/CreatePresignedUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uploadClient) UploadedWebhook(ctx context.Context, in *UploadedWebhookRequest, opts ...grpc.CallOption) (*UploadedWebhookResponse, error) {
	out := new(UploadedWebhookResponse)
	err := c.cc.Invoke(ctx, "/upload.Upload/UploadedWebhook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UploadServer is the server API for Upload service.
// All implementations must embed UnimplementedUploadServer
// for forward compatibility
type UploadServer interface {
	CreatePresignedUrl(context.Context, *CreatePresignedUrlRequest) (*CreatePresignedUrlResponse, error)
	UploadedWebhook(context.Context, *UploadedWebhookRequest) (*UploadedWebhookResponse, error)
	mustEmbedUnimplementedUploadServer()
}

// UnimplementedUploadServer must be embedded to have forward compatible implementations.
type UnimplementedUploadServer struct {
}

func (UnimplementedUploadServer) CreatePresignedUrl(context.Context, *CreatePresignedUrlRequest) (*CreatePresignedUrlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePresignedUrl not implemented")
}
func (UnimplementedUploadServer) UploadedWebhook(context.Context, *UploadedWebhookRequest) (*UploadedWebhookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadedWebhook not implemented")
}
func (UnimplementedUploadServer) mustEmbedUnimplementedUploadServer() {}

// UnsafeUploadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UploadServer will
// result in compilation errors.
type UnsafeUploadServer interface {
	mustEmbedUnimplementedUploadServer()
}

func RegisterUploadServer(s grpc.ServiceRegistrar, srv UploadServer) {
	s.RegisterService(&Upload_ServiceDesc, srv)
}

func _Upload_CreatePresignedUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePresignedUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadServer).CreatePresignedUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/upload.Upload/CreatePresignedUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadServer).CreatePresignedUrl(ctx, req.(*CreatePresignedUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Upload_UploadedWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadedWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UploadServer).UploadedWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/upload.Upload/UploadedWebhook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UploadServer).UploadedWebhook(ctx, req.(*UploadedWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Upload_ServiceDesc is the grpc.ServiceDesc for Upload service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Upload_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "upload.Upload",
	HandlerType: (*UploadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePresignedUrl",
			Handler:    _Upload_CreatePresignedUrl_Handler,
		},
		{
			MethodName: "UploadedWebhook",
			Handler:    _Upload_UploadedWebhook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/upload/upload.proto",
}
